from .MnistDataLoader import MnistDataLoader
from .projects.ProstateClassDataLoader import ProstateClassDataLoader
from .projects.ADNIDataLoader import ADNIDataLoader, ADNIMultimodalDataLoader
from .projects.RetinaDataLoader import RetinaDataLoader
from .projects.ChaimeleonProstateDataLoader import ChaimeleonProstateDataLoader