from .MnistDataLoader import MnistDataLoader
from .projects.ADNIDataLoader import ADNIDataLoader, ADNIMultimodalDataLoader
from .projects.ChaimeleonProstateDataLoader import ChaimeleonProstateDataLoader
from .projects.ProstateClassDataLoader import ProstateClassDataLoader
from .projects.ProstateSegDataLoader import ProstateSegDataLoader
from .projects.RetinaDataLoader import RetinaDataLoader
